CREATE TABLE migrations (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number integer not null,
    name varchar(200) not null,
    inserted_at TIMESTAMP WITHOUT TIME ZONE DEFAULT (CURRENT_TIMESTAMP at time zone 'utc')
);
