CREATE TABLE IF NOT EXISTS users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(64) not null,
    password_digest varchar(200) not null,
    email    varchar(64),
    is_active boolean default true,
    avatar varchar(200) null,
    inserted_at TIMESTAMP WITHOUT TIME ZONE DEFAULT (CURRENT_TIMESTAMP at time zone 'utc'),
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT (CURRENT_TIMESTAMP at time zone 'utc')
);

CREATE UNIQUE INDEX IF NOT EXISTS users_username_unique_index ON users USING btree (username);
CREATE UNIQUE INDEX IF NOT EXISTS users_email_unique_index ON users USING btree (email);