CREATE TYPE tparty AS ENUM ('auth');

CREATE TABLE IF NOT EXISTS third_party (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(200) not null,
    code varchar(64) not null,
    type tparty not null,
    is_active boolean default true,
    inserted_at TIMESTAMP WITHOUT TIME ZONE DEFAULT (CURRENT_TIMESTAMP at time zone 'utc'),
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT (CURRENT_TIMESTAMP at time zone 'utc')
);

CREATE UNIQUE INDEX third_party_code_unique ON third_party USING btree(code);

INSERT INTO third_party
    (name, code, type, is_active)
VALUES
    ('Github', 'github', 'auth', true);